server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://${MYSQL_URL}
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true


logging:
  level:
    org.hibernate.SQL: debug
