server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # TODO: flyway 추가

  jpa:
    hibernate:
      ddl-auto: update  #create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  output:
    ansi.enabled: always

logging:
  level:
    org.hibernate.SQL: debug
