version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: hong
      MYSQL_PASSWORD: hong
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: community-db
      TZ: 'Asia/Seoul'
    volumes:
      - community-mysqldb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  community-mysqldb:
