name: 백엔드 CI

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  checks: write
  pull-requests: write

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 테스트 코드 실행
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: test
